on:
  push:
    branches:
      - master
      - 'releases/**'
jobs:
  build:
    runs-on: self-hosted
    steps:
        - name: Checkout from repo
          uses: actions/checkout@v3
        - name: Build with docker
          run: docker build -t ${{ secrets.PRIV_REPO }}/sites/yorqat:latest
        - name: Push
          run: docker push ${{ secrets.PRIV_REPO }}/sites/yorqat:latest