on:
  push:
    branches:
      - master
      - 'releases/**'
jobs:
  build:
    runs-on: self-hosted
    steps:
        - name: Checkout from repo
          uses: actions/checkout@v3
        - name: Setup Node.js environment
          uses: actions/setup-node@v3.6.0
          with:
            node-version: 19.6.0
        - name: Build node app
          run: | 
            npm ci
            npm run build
        - name: Test node app
          run: | 
            npx playwright install 
            npm run test
