on:
  push:
    branches:
      - master
      - 'releases/**'
jobs:
  deploy:
    runs-on: self-hosted
    container:
      image: bitnami/kubectl:1.26.3-debian-11-r0
    steps:
        - name: Checkout from repo
          uses: actions/checkout@v3
        - name: Build and push
          run: |
            docker build -t ${{ secrets.OCI_IMAGE }}:latest .
            docker push ${{ secrets.OCI_IMAGE }}:latest
            # Current limitation of docker not being inside the cotainer
            # docker rmi ${{ secrets.OCI_IMAGE }}:latest
        # - name: Setup kubectl
        #   run: |
        #     curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
        #     echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
        #     apt-get update
        #     apt-get install -y kubectl
        - name: Create kube config
          run: |
            # Install our k8s credentials
            mkdir ${HOME}/.kube
            echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ${HOME}/.kube/config
        - name: Up the deployment
          run: |
            # Delete the current deployment
            kubectl delete deploy www-yorqat -n sites
            # To substitute yaml file with envsubst, secret needs 
            # to be re-exported to a bash variable
            export OCI_IMAGE="${{ secrets.OCI_IMAGE }}"
            envsubst < k8s/deploy.yml | kubectl apply -f -