on: 
  workflow_dispatch

jobs:
  ingress:
    runs-on: ubuntu-latest
    steps:
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      id: install
    - name: Create kube config
      run: |
        mkdir ${HOME}/.kube
        echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
    # - name: Apply ingress
    #   run: |
    #     envsubst < k8s/ingress.yml | kubectl apply -f -