on:
  workflow_dispatch
jobs:
  rsync:
    runs-on: eye-cluster
    steps:
      - name: Install rsync  
        uses:  GuillaumeFalourd/setup-rsync@v1.1
        
      - name: rsync from staging to prod
        run: |
            echo "${{secrets.CORNEA_SSH_KEY}}" | base64 --decode > /sshkey
            chmod 600 /sshkey
            rsync -e "ssh -o StrictHostKeyChecking=no -i /sshkey" -avz --verbose ${{secrets.PERSISTENT_VOLUME}}/staging-www.yorqat.com.pvc/ ${{secrets.PERSISTENT_VOLUME}}/prod.www.yorqat.com.pvc/