on:
  workflow_dispatch
jobs:
  rsync:
    runs-on: eye-cluster
    steps:
      - name: Install rsync  
        uses:  GuillaumeFalourd/setup-rsync@v1.1
        
      - name: rsync from staging to prod
        run: |
            echo "${{secrets.CORNEA_SSH_KEY}}" | base64 --decode > /sshkey
            chmod 600 /sshkey
            rsync -e "ssh -o StrictHostKeyChecking=no -i /sshkey" -avz --verbose ${{secrets.PERSISTENT_VOLUME}}/staging-www.yorqat.com.pvc/ build/
            rsync -e "ssh -o StrictHostKeyChecking=no -i /sshkey" -avz --verbose build/ ${{secrets.PERSISTENT_VOLUME}}/prod.www.yorqat.com.pvc/
  
  rollout-restart:
      runs-on: eye-cluster
      needs: rsync
      steps:
      - name: Setup kubectl
        run: |
          apt-get update
          apt install -y apt-transport-https ca-certificates curl
          curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/kubernetes-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
          apt-get update
          apt-get install -y kubectl

      - name: Create kube config
        run: |
          mkdir ${HOME}/.kube
          echo "${{ secrets.CLUSTER_CONF }}" | base64 --decode > ${HOME}/.kube/config

      - name: Rollout restart cluster
        run: |
          kubectl -n prod rollout restart deploy www.yorqat.com
